#!/bin/bash
# Script helper para carregar variáveis de ambiente
# Uso: source config/load_env.sh

set -a  # Export todas as variáveis automaticamente
source "$(dirname "${BASH_SOURCE[0]}")/env.config"
set +a  # Desligar export automático

# Cores para output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🔧 Variáveis de ambiente carregadas:${NC}"
echo -e "${GREEN}✅ PostgreSQL Source: ${POSTGRES_SOURCE_USER}@localhost:${POSTGRES_SOURCE_PORT}/${POSTGRES_SOURCE_DB}${NC}"
echo -e "${GREEN}✅ PostgreSQL Target: ${POSTGRES_TARGET_USER}@localhost:${POSTGRES_TARGET_PORT}/${POSTGRES_TARGET_DB}${NC}"
echo -e "${GREEN}✅ DBT: Conectando temporariamente ao SOURCE (${DBT_SOURCE_USER}@${DBT_SOURCE_HOST})${NC}"
echo -e "${GREEN}✅ Airbyte: admin@localhost:${AIRBYTE_WEBAPP_PORT}${NC}"
echo -e "${GREEN}✅ MinIO: ${MINIO_ROOT_USER}@localhost:${MINIO_CONSOLE_PORT}${NC}"
echo -e "${GREEN}✅ APIs: E-commerce:${ECOMMERCE_API_PORT} | CRM:${CRM_API_PORT}${NC}"

# Exportar variáveis para docker-compose
export POSTGRES_SOURCE_USER POSTGRES_SOURCE_PASSWORD POSTGRES_SOURCE_DB POSTGRES_SOURCE_PORT
export POSTGRES_TARGET_USER POSTGRES_TARGET_PASSWORD POSTGRES_TARGET_DB POSTGRES_TARGET_PORT  
export AIRBYTE_DB_USER AIRBYTE_DB_PASSWORD AIRBYTE_DB_NAME
export MINIO_ROOT_USER MINIO_ROOT_PASSWORD MINIO_CONSOLE_PORT MINIO_API_PORT
export DBT_TARGET_TYPE 
export DBT_SOURCE_HOST DBT_SOURCE_PORT DBT_SOURCE_USER DBT_SOURCE_PASSWORD DBT_SOURCE_DB DBT_SOURCE_SCHEMA
export DBT_TARGET_HOST DBT_TARGET_PORT DBT_TARGET_USER DBT_TARGET_PASSWORD DBT_TARGET_DB DBT_TARGET_SCHEMA
export AIRBYTE_WEBAPP_PORT AIRBYTE_SERVER_PORT
export POSTGRES_WAL_LEVEL POSTGRES_MAX_WAL_SENDERS POSTGRES_MAX_REPLICATION_SLOTS POSTGRES_MAX_LOGICAL_REPLICATION_WORKERS
export MINIO_BUCKET_BRONZE MINIO_BUCKET_SILVER MINIO_BUCKET_GOLD MINIO_BUCKET_AIRBYTE