version: 2

models:
  - name: dim_clientes
    description: >
      Dimensão de clientes. Contém dados limpos e transformados,
      prontos para uso em análises e modelagem dimensional.
    columns:
      - name: cliente_id
        description: Identificador único do cliente
        tests:
          - unique
          - not_null
      - name: nome
        description: Nome completo do cliente (limpo e padronizado)
        tests:
          - not_null
      - name: email_original
        description: Email original do cliente
        tests:
          - not_null
          - unique
      - name: data_cadastro
        description: Data e hora de cadastro do cliente
      - name: ultima_atualizacao
        description: Data e hora da última atualização dos dados do cliente
      - name: data_ingestao_airbyte
        description: Data e hora em que o registro foi ingerido pelo Airbyte

  - name: fct_pedidos
    description: >
      Fato de pedidos. Contém dados limpos e transformados,
      com métricas calculadas como valor_total_pedido.
    columns:
      - name: pedido_id
        description: Identificador único do pedido
        tests:
          - unique
          - not_null
      - name: cliente_id
        description: Identificador do cliente que fez o pedido
        tests:
          - not_null
          - relationships:
              to: ref('dim_clientes')
              field: cliente_id
      - name: nome_cliente
        description: Nome do cliente, para facilitar análises
      - name: numero_pedido
        description: Número do pedido
        tests:
          - not_null
      - name: valor_bruto
        description: Valor bruto do pedido
        tests:
          - not_null
      - name: valor_liquido
        description: Valor líquido do pedido após descontos
        tests:
          - not_null
      - name: data_pedido
        description: Data e hora em que o pedido foi registrado
      - name: ano_pedido
        description: Ano extraído da data do pedido
      - name: mes_pedido
        description: Mês extraído da data do pedido
      - name: dia_pedido
        description: Dia extraído da data do pedido
      - name: data_ultima_atualizacao_pedido
        description: Data e hora da última atualização dos dados do pedido
      - name: data_ingestao_airbyte
        description: Data e hora em que o registro foi ingerido pelo Airbyte
        
  - name: silver_clientes
    description: >
      Modelo Silver para clientes com enriquecimentos e dados derivados.
    columns:
      - name: cliente_id_origem
        description: Identificador único do cliente na origem
        tests:
          - unique
          - not_null
      - name: nome_completo
        description: Nome completo do cliente padronizado em Title Case
      - name: email_padronizado
        description: Email padronizado em lowercase
      - name: data_cadastro_ts
        description: Timestamp de cadastro do cliente
      - name: ultima_atualizacao_ts
        description: Timestamp da última atualização
      - name: data_replicacao_airbyte
        description: Data e hora da replicação pelo Airbyte
      - name: dominio_email
        description: Domínio extraído do email do cliente
      - name: ano_cadastro
        description: Ano de cadastro do cliente
        
  - name: silver_pedidos
    description: >
      Modelo Silver para pedidos com cálculos e dados derivados.
    columns:
      - name: pedido_id_origem
        description: Identificador único do pedido na origem
        tests:
          - unique
          - not_null
      - name: cliente_id_origem
        description: Identificador do cliente que fez o pedido
        tests:
          - not_null
      - name: produto_nome
        description: Nome do produto padronizado
      - name: valor_bruto_decimal
        description: Valor bruto do pedido como decimal
        tests:
          - not_null
      - name: valor_liquido_decimal
        description: Valor líquido do pedido como decimal
        tests:
          - not_null
      - name: data_pedido_ts
        description: Timestamp do pedido
      - name: ultima_atualizacao_ts
        description: Timestamp da última atualização
      - name: data_replicacao_airbyte
        description: Data e hora da replicação pelo Airbyte
      - name: ano_pedido
        description: Ano do pedido
      - name: mes_pedido
        description: Mês do pedido
      - name: dia_pedido
        description: Dia do pedido
